name: Cypress Tests
run-name: ${{ github.actor }} is running Cypress tests 
on: [push]
jobs:
    basic-ubuntu-20:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Cypress tests
          run: npx cypress run
          env:
            CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}