name: Cypress Tests
run-name: ${{ github.actor }} is running Cypress tests 
on: [push]
jobs:
    basic-ubuntu-20:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Cypress tests
          uses: ./
          with:
            working-directory: cypress
            build: npx cypress info
  